### ISSUE TITLE
You guys are aware of https://irc.gitter.im/ ?

### ISSUE THREAD

**Issue by Carreau** [xonsh/xonshbot#1]
Right ?

---

Snippet for the lazy:

"I'm connected from my VT100" - Chuck Norris
what is Gitter?

man irc.gitter.im (this service is still very much beta)
1. Click here to login and get your token
2. Connect to irc.gitter.im with your IRC client using SSL(port 6667 or 6697)
3. Provide the the token we give you (login to see token) as the Server Password
4. /NICK your github username
5. Profit

100% compatible with Lynx. Seriously.

**Comment by adqm** [comment]
Yes.  The problem I had with irc.gitter.im is that the IRC feed streams _all events_  (e.g., someone stars the repo, someone comments on an issue, etc) in addition to all chat messages.  I couldn't stand the clutter.

Plus, for those that want the IRC experience, I think it's easier to tell them to connect to OFTC than it is to tell them to go to irc.gitter.im, find their token, configure their client to use the token, etc.

**Comment by Carreau** [comment]
ok, thanksfor explanation
