### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by adqm** [xonsh/xonshbot#4]
In the current setup, the bot _really_ wants to use up all those spare CPU cycles.  I'm not quite sure where exactly it is spinning, but if it's in waiting for input from the servers, smart use of `select` is one potential solution.

**Comment by adqm** [comment]
Actually, it looks like under normal operating conditions, its CPU usage isn't so bad (since we're blocking on all socket reads).  But something caused it to jump up to 100% CPU usage on one run, and to stay there.  Maybe something weird happens on an error?

**Comment by scopatz** [comment]
just out of curiosity, where is this being run at? 😂

**Comment by adqm** [comment]
Currently, on a VPS of mine.  I don't have a whole lot else going on on that server, so it's alright if it goes a little crazy.

**Comment by scopatz** [comment]
Ahh I see. Cool.

**Comment by adqm** [comment]
Seems that this isn't an issue during normal operation (been running all day with no problems).  Closing for now.
